# Generated by Django 4.2 on 2023-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_pircture_happys_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('place', models.CharField(max_length=100)),
                ('properties', models.IntegerField()),
            ],
        ),
    ]
